import Foundation
public struct LMRMViewMethon {
    public static let topCollectAction: String = "topCollectAction"
    public static let topNoticeAction: String = "topNoticeAction"
    public static let topOnlineUserAction: String = "topOnlineUserAction"
    public static let seatClickAction: String = "seatClickAction"
    public static let onGuestSeatAction: String = "onGuestSeatAction"
    public static let releaseDispatchAction: String = "releaseDispatchAction"
    public static let clickViewDispatchAction: String = "clickViewDispatchAction"
    public static let dRSortAction: String = "dRSortAction"
    public static let pkDidClickStartOrEndAction: String = "pkDidClickStartOrEndAction"
    public static let bottomSeatAction: String = "bottomSeatAction"
    public static let showSortViewAction: String = "showSortViewAction"
    public static let clickMegViewAction: String = "clickMegViewAction"
    public static let clickGiftAction: String = "clickGiftAction"
    public static let clickMoreAction: String = "clickMoreAction"
    public static let clickMsgListAction: String = "clickMsgListAction"
    public static let rankShowRankRuleAction: String = "rankShowRankRuleAction"
    public static let rankViewUserAction: String = "rankViewUserAction"
    public static let chatListClickUser: String = "chatListClickUser"
    public static let chatListWelcomeUser: String = "chatListWelcomeUser"
    public static let bannerDidClickItem: String = "bannerDidClickItem"
    public static let invitebtnClick: String = "invitebtnClick"
    public static let invitebtnShow: String = "invitebtnShow"
    public static let roomPKendAction: String = "roomPKendAction"
    public static let redRoomAction: String = "redRoomAction"
    public static let roomHatAction: String = "roomHatAction"
    public static let clickmicMuteAction: String = "clickmicMuteAction"
    public static let topRankAction: String = "topRankAction"
    public static let moreViewMethon: String = "moreViewMethon"
    public static let removeUserSeatSort: String = "removeUserSeatSort"
    public static let holdUserOnSeat: String = "holdUserOnSeat"

    
}
